# Generated by Django 4.1.1 on 2022-09-13 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(error_messages={'error': 'This email already exists!'}, max_length=254, unique=True)),
                ('username', models.CharField(error_messages={'error': 'This username already exists!'}, max_length=128, unique=True)),
                ('password', models.CharField(error_messages={'error': 'Password must contain at least 8 characters'}, max_length=128, validators=[django.core.validators.MinLengthValidator(8)])),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, default='profile/default.jpg', upload_to='profile/avatar')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
