# Generated by Django 4.1.1 on 2022-10-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='post_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
