# Generated by Django 4.1.1 on 2022-10-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_post_comments_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments_count',
            field=models.IntegerField(verbose_name='Total Comments'),
        ),
    ]
